name: First Workflow

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  job_1:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - name: Set variable
        run: | 
          echo "pull_request : ${{ github.event.pull_request }}"
          echo "{myVariable}={111}" >> $GITHUB_OUTPUT
          echo "{myVariable}={111}" > 1.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: 1.txt
              
  
  job_2:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      #- name: Download artifact
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: my-artifact
      - name: Checkout code to (local) repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: gh workflow list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
        