name: First Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set variable
        run: | 
          echo "{myVariable}={111}" >> $GITHUB_OUTPUT
          echo "{myVariable}={111}" > 1.txt
          ls -lart


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: 1.txt
              