name: Second Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Intermediate Workflow
        uses: ./.github/workflows/First Workflow
        #uses: ./.github/workflows/intermediate-workflow

      - name: Use Intermediate Output
        run: echo "The intermediate variable is ${{ steps.setOutput.outputs.intermediateVariable }}"