name: Workflow 1

on:
  pull_request:
    branches:
      - main

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      #- run: mkdir -p path/to/artifact
      
      - run: echo hello > world.txt
      - run: ${{ runner.workspace }}  
      
      
      - uses: actions/upload-artifact@v3
        with: 
          name: art1
          path: world.txt 
      


      #- name: Upload artifact
      #  uses: actions/upload-artifact@v2
      #  with: 
      #    name: my-artifact
      #    path: ${{ runner.workspace }}  
        

            
