name: Workflow 2

on:
  pull_request:
    types:
      - closed
    
      
jobs:
  job_1:
    runs-on: ubuntu-latest
    # local env
    steps:
      - name: Log ENV Variables
        run: |
          ls -l 
                 
            
        

            
