name: Workflow 1

on:
  pull_request:
    branches:
      - main

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - run: mkdir -p path/to/artifact
      
      - run: echo hello > path/to/artifact/world.txt
      
      - uses: actions/upload-artifact@v3
        with: 
          name: my-artifact
          path: path/to/artifact/world.txt 
      


      #- name: Upload artifact
      #  uses: actions/upload-artifact@v2
      #  with: 
      #    name: my-artifact
      #    path: ${{ runner.workspace }}  
        

            
