name: Workflow 2

on:
  pull_request:
    types:
      - closed
    
      
jobs:
  get-artifacts:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: world
          
      - name: Extract artifact
        run: ls -R

      - run: env
            
      

            
