name: Workflow 2

on:
  pull_request:
    types:
      - closed
    
      
jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: my-artifact
          
      - name: Extract artifact
        run: ls -R

      - run: cat "$GITHUB_OUTPUT"  
            
        

            
