name: Workflow 1

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set var
        run: echo "::set-output name=myVar::alex"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: my-artifact
          path: ${{ runner.workspace }}  
        

            
