name: Workflow 2

on:
  pull_request:
    types:
      - closed
    
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: 
          name: my-artifact
          
      - name: Extract artifact
        run: |
          tar -xf my-artifact
          cat extracted-workflow-output.txt    
        

            
